---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gundawar/cf-cli
    tag: latest
inputs:
  - name: cfusagerepo
outputs:
  - name: email
run:
  path: cfusagerepo/ci/scripts/usage-script.sh
  args:
  - -exc
  - |
    env
    echo "Enough CF Memory is there"
