API_URL:  https://api.system.dip-sandbox-east.sonicdrivein-sandbox.digital
USERNAME: admin
PASSWORD: KvqvicNgrr0h8qdTgbHNqyVBs7MXio_t
SMTP: smtp.gmail.com
FROM: rajesh.gundawar@techolution.com
USR: rajesh.gundawar@techolution.com
PAS: $unFl0wer1
PORT: 587
TO: rajesh.gundawar@techolution.com
ENV: sandbox
ORG: sonic
THRESHOLD: 10
